baseURL = "https://sebkraemer.github.io/"
publishDir = "public"
languageCode = "en-us"
title = "TL;DR dev blog"
author = "Sebastian Kr√§mer"
theme = "hugo-vitae"

# Navigation
[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2
